-- ==============================================================================
-- SCRIPT DDL SUPABASE - PROJETO VERSUSHUB
-- Cole este script no SQL Editor do painel do Supabase (https://supabase.com/dashboard)
-- ==============================================================================

-- 1. TABELA DE USUÁRIOS
CREATE TABLE IF NOT EXISTS public.usuarios (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    nome TEXT NOT NULL,
    email TEXT NOT NULL UNIQUE,
    senha TEXT NOT NULL,
    "dataNasc" TEXT,
    bio TEXT DEFAULT '',
    avatar TEXT DEFAULT '/image/boneco_logo_ofc.png',
    regiao TEXT DEFAULT 'Brasil',
    "jogosFavoritos" JSONB DEFAULT '[]'::jsonb,
    plataformas JSONB DEFAULT '[]'::jsonb,
    banner TEXT DEFAULT '',
    stats JSONB DEFAULT '{"disputed": 0, "won": 0, "wins": 0, "losses": 0}'::jsonb,
    conquistas JSONB DEFAULT '[{"titulo": "Perfil Ativado", "desc": "Configure e atualize suas conquistas para o ranking no painel de perfil.", "data": "Desbloqueado"}]'::jsonb,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. TABELA DE TORNEIOS
CREATE TABLE IF NOT EXISTS public.torneios (
    id TEXT PRIMARY KEY,
    nome TEXT NOT NULL,
    jogo TEXT,
    data TEXT,
    status TEXT DEFAULT 'Inscrições abertas',
    "statusClass" TEXT DEFAULT 'status-aberto',
    banner TEXT,
    "criadorEmail" TEXT,
    descricao TEXT,
    categoria TEXT,
    plataforma TEXT,
    "inicioIso" TEXT,
    localizacao TEXT,
    modalidade TEXT DEFAULT 'online',
    regras TEXT,
    "taxaTipo" TEXT DEFAULT 'gratis',
    "taxaValor" TEXT DEFAULT '',
    "tipoPremio" TEXT DEFAULT 'nenhuma',
    premio1 TEXT DEFAULT '',
    premio2 TEXT DEFAULT '',
    premio3 TEXT DEFAULT '',
    "premiacaoExtra" TEXT DEFAULT '',
    requisitos TEXT DEFAULT '',
    link TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. TABELA DE EQUIPES
CREATE TABLE IF NOT EXISTS public.equipes (
    id TEXT PRIMARY KEY,
    nome TEXT NOT NULL,
    tag TEXT,
    jogos TEXT,
    plataforma TEXT,
    regiao TEXT,
    limite TEXT,
    sobre TEXT DEFAULT 'Nenhuma descrição informada.',
    logo TEXT DEFAULT '/image/logo.png',
    "leaderName" TEXT,
    "leaderAvatar" TEXT,
    "leaderEmail" TEXT,
    "torneiosGanhos" JSONB DEFAULT '[]'::jsonb,
    "torneiosAtuais" JSONB DEFAULT '[]'::jsonb,
    link TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 4. TABELA DE CURTIDAS (LIKES)
CREATE TABLE IF NOT EXISTS public.curtidas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    torneio_id TEXT NOT NULL,
    user_email TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    CONSTRAINT curtidas_torneio_user_unique UNIQUE (torneio_id, user_email)
);

-- 5. TABELA DE INSCRIÇÕES
CREATE TABLE IF NOT EXISTS public.inscricoes (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    torneio_id TEXT NOT NULL,
    user_email TEXT NOT NULL,
    tipo TEXT DEFAULT 'individual',
    id_participante TEXT,
    status TEXT DEFAULT 'Pendente',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    CONSTRAINT inscricoes_torneio_user_unique UNIQUE (torneio_id, user_email)
);

-- 6. TABELA DE MEMBROS DE EQUIPE
CREATE TABLE IF NOT EXISTS public.membros_equipe (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    equipe_id TEXT NOT NULL,
    user_email TEXT NOT NULL,
    status TEXT DEFAULT 'Pendente',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    CONSTRAINT membros_equipe_user_unique UNIQUE (equipe_id, user_email)
);

-- Índices para otimização de consultas frequentes
CREATE INDEX IF NOT EXISTS idx_usuarios_email ON public.usuarios(email);
CREATE INDEX IF NOT EXISTS idx_curtidas_torneio ON public.curtidas(torneio_id);
CREATE INDEX IF NOT EXISTS idx_curtidas_user ON public.curtidas(user_email);
CREATE INDEX IF NOT EXISTS idx_inscricoes_torneio ON public.inscricoes(torneio_id);
CREATE INDEX IF NOT EXISTS idx_inscricoes_user ON public.inscricoes(user_email);
CREATE INDEX IF NOT EXISTS idx_membros_equipe_id ON public.membros_equipe(equipe_id);
CREATE INDEX IF NOT EXISTS idx_membros_equipe_user ON public.membros_equipe(user_email);
CREATE INDEX IF NOT EXISTS idx_equipes_leader ON public.equipes("leaderEmail");
CREATE INDEX IF NOT EXISTS idx_torneios_criador ON public.torneios("criadorEmail");

-- ==============================================================================
-- POLÍTICAS DE ACESSO (Row Level Security - RLS)
-- Permite operações com a chave pública anônima (anon key) no Vanilla JS
-- ==============================================================================

ALTER TABLE public.usuarios ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.torneios ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.equipes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.curtidas ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.inscricoes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.membros_equipe ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Acesso público usuarios" ON public.usuarios;
CREATE POLICY "Acesso público usuarios" ON public.usuarios
    FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Acesso público torneios" ON public.torneios;
CREATE POLICY "Acesso público torneios" ON public.torneios
    FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Acesso público equipes" ON public.equipes;
CREATE POLICY "Acesso público equipes" ON public.equipes
    FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Acesso público curtidas" ON public.curtidas;
CREATE POLICY "Acesso público curtidas" ON public.curtidas
    FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Acesso público inscricoes" ON public.inscricoes;
CREATE POLICY "Acesso público inscricoes" ON public.inscricoes
    FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Acesso público membros_equipe" ON public.membros_equipe;
CREATE POLICY "Acesso público membros_equipe" ON public.membros_equipe
    FOR ALL USING (true) WITH CHECK (true);

-- ==============================================================================
-- SEED DATA: Usuários e Torneios para testes imediatos
-- ==============================================================================

INSERT INTO public.usuarios (nome, email, senha, "dataNasc", bio, avatar)
VALUES
    (
        'Caíque Brandão',
        'caique@gmail.com',
        '123',
        '2008-01-01',
        'Opa me chamo Caíque, tenho 18 anos, amo jogos, principalmente Brawl Stars e Fortnite. Curto um bom Rock e amo uma resenha',
        '/equipes/images/caiquebrandao.jpg'
    ),
    (
        'zZ_Dinho_Winchexxter_Zz',
        'dinho@gmail.com',
        '123',
        '1999-05-15',
        'Fala aí, eu sou o Dinho. Curto jogar FPS e participar de campeonatos on-line.',
        '/equipes/images/dinhowinches.jpg'
    ),
    (
        'Mar_cuzcuz',
        'marcuzcuz@gmail.com',
        '123',
        '2000-11-20',
        'Eu sou o Marcuzcuz, gosto de Cuzcuz, galinhas e do Vasco.',
        '/equipes/images/marcuzcuz.jpg'
    )
ON CONFLICT (email) DO NOTHING;

INSERT INTO public.torneios (id, nome, jogo, data, status, "statusClass", banner, categoria, plataforma, link)
VALUES
    (
        'cerrado-cup',
        'Cerrado Cup CS:GO',
        'CS:GO',
        '22/03/2026',
        'Inscrições abertas',
        'status-aberto',
        '/images/cerradocup.jpg',
        'fps',
        'pc',
        '/torneio/detalhes-cerradocup.html'
    ),
    (
        'contra-cup',
        'Contra Cup Free Fire',
        'Free Fire',
        '01/03/2026',
        'Em andamento',
        'status-andamento',
        '/images/contracup.jpeg',
        'battle-royale',
        'mobile',
        '/torneio/custom.html?id=contra-cup'
    ),
    (
        'liga-ff',
        'Liga FF Brasil',
        'Free Fire',
        '29/02/2026',
        'Encerrado',
        'status-encerrado',
        '/images/liga-ff-brasil.jpeg',
        'battle-royale',
        'mobile',
        '/torneio/custom.html?id=liga-ff'
    ),
    (
        'fifa-global-series',
        'FIFA Global Series',
        'FIFA',
        '22/02/2026',
        'Inscrições abertas',
        'status-aberto',
        '/images/fifa23_globalseries.webp',
        'esportes',
        'console',
        '/torneio/detalhes-fifaglobalseries.html'
    ),
    (
        'gamescom-latam',
        'Gamescom Latam CS:GO',
        'CS:GO',
        '01/04/2026',
        'Inscrições abertas',
        'status-aberto',
        '/pagina_inicial/image/gamescom_latam.webp',
        'fps',
        'pc',
        '/torneio/custom.html?id=gamescom-latam'
    ),
    (
        'parana-startups',
        'Paraná Startups Challenge',
        'CS:GO',
        '15/03/2026',
        'Em andamento',
        'status-andamento',
        '/pagina_inicial/image/parana.jpg',
        'fps',
        'pc',
        '/torneio/custom.html?id=parana-startups'
    ),
    (
        'evo-csgo',
        'Evo Championship Series CS:GO',
        'CS:GO',
        '10/02/2026',
        'Encerrado',
        'status-encerrado',
        '/pagina_inicial/image/evolution-championship-series.jpg',
        'fps',
        'pc',
        '/torneio/custom.html?id=evo-csgo'
    ),
    (
        'evo-ff',
        'Evo Championship Series Free Fire',
        'Free Fire',
        '05/04/2026',
        'Inscrições abertas',
        'status-aberto',
        '/pagina_inicial/image/evoff.jpg',
        'battle-royale',
        'mobile',
        '/torneio/custom.html?id=evo-ff'
    ),
    (
        'copa-ff',
        'C.O.P.A - Free Fire',
        'Free Fire',
        '18/04/2026',
        'Inscrições abertas',
        'status-aberto',
        '/pagina_inicial/image/copaff.jpg',
        'battle-royale',
        'mobile',
        '/torneio/custom.html?id=copa-ff'
    )
ON CONFLICT (id) DO NOTHING;

-- SEED DAS EQUIPES INICIAIS
INSERT INTO public.equipes (id, nome, tag, jogos, plataforma, regiao, limite, sobre, logo, "leaderName", "leaderAvatar", link)
VALUES
    ('viltrumitas', 'Viltrumitas', 'VLT', 'Valorant', 'pc', 'BR', '6', 'Equipe competitiva de Valorant com foco em torneios de alto nível.', '/equipes/image/Viltrumitas.jpg', 'OmniMan', '/equipes/image/Viltrumitas.jpg', '/equipes/detalhes-viltrumitas.html'),
    ('the-caras', 'The Caras', 'CRS', 'CS2', 'pc', 'BR', '4', 'Time experiente de CS2 pronto para dominar as ligas.', '/equipes/image/the%20caras.png', 'Butcher', '/equipes/image/the%20caras.png', '/equipes/detalhes-thecaras.html'),
    ('the-jacksons', 'The Jacksons', 'JKS', 'Free Fire', 'mobile', 'BR', '10', 'Squad tático de Free Fire focado em rush e posicionamento.', '/equipes/image/jacksons.png', 'Jackson', '/equipes/image/jacksons.png', '/equipes/detalhes-thejacksons.html'),
    ('os-vagalumes', 'Os Vagalumes', 'VGL', 'Fortnite', 'console', 'BR', '5', 'Construção rápida e precisão cirúrgica no Fortnite.', '/equipes/image/vagalumes.png', 'Firefly', '/equipes/image/vagalumes.png', '/equipes/detalhes-vagalumes.html'),
    ('shadow-foxes', 'Shadow Foxes', 'SFX', 'Valorant', 'pc', 'BR', '6', 'Estratégia e furtividade nos mapas competitivos de Valorant.', '/equipes/image/shadow_foxes.png', 'Fox', '/equipes/image/shadow_foxes.png', '/equipes/detalhes-shadowfoxes.html'),
    ('sky-titans', 'Sky Titans', 'SKT', 'CS2', 'pc', 'BR', '5', 'Equipe de mira afiada e comunicação limpa no CS2.', '/equipes/image/sky_titans.png', 'Titan', '/equipes/image/sky_titans.png', '/equipes/detalhes-skytitans.html'),
    ('dark-wolves', 'Dark Wolves', 'DW', 'Free Fire', 'mobile', 'BR', '5', 'Alcateia implacável pronta para conquistar cada safe zone.', '/equipes/image/dark_wolves.png', 'Alpha', '/equipes/image/dark_wolves.png', '/equipes/detalhes-darkwolves.html'),
    ('royal-dragons', 'Royal Dragons', 'RDG', 'Valorant', 'pc', 'BR', '5', 'Domínio do mapa e execuções perfeitas no Valorant.', '/equipes/image/royal_dragons.png', 'Dragon', '/equipes/image/royal_dragons.png', '/equipes/detalhes-royaldragons.html'),
    ('red-vipers', 'Red Vipers', 'RVP', 'CS2', 'pc', 'BR', '5', 'Agressividade calculada e precisão nos confrontos diretos.', '/equipes/image/red_vipers.png', 'Viper', '/equipes/image/red_vipers.png', '/equipes/detalhes-redvipers.html'),
    ('storm-riders', 'Storm Riders', 'STR', 'Fortnite', 'console', 'BR', '5', 'Velocidade e controle da tempestade nas partidas de Fortnite.', '/equipes/image/storm_riders.png', 'Rider', '/equipes/image/storm_riders.png', '/equipes/detalhes-stormriders.html')
ON CONFLICT (id) DO NOTHING;

